### ISSUE TITLE
Python 聊天室

### ISSUE THREAD

**Issue by xdqi** [hghwng/homework-14#17]
course: 'Python'
deadline: '2016-04-13'
submit: 课上收纸质版报告

---

创建一个简单的，半双工的聊天程序。“半双工”的意思是当创建一个连接，服务启动的时候，只有一个人可以打字，另一个人只有在等到有消息通知他输入消息时，才能说话。一旦消息发送出去后，要等到有回复了才能发送下一条消息。一个人是服务端，另一个人是客户端。

1. 半双工聊天。在本地记录通信双方的消息日志（时间，通信内容等）。
2. 增加“名字服务器”，即客户端首先连接“名字服务器”，从名字服务器获得服务端的 IP 地址和端口，然后客户端建立与服务器的通讯连接，进行通讯。

**Comment by hghwng** [comment]
晓东大大辛苦啦！
